### ISSUE TITLE
Henson / Python exception when setting sys.argv

### ISSUE THREAD

**Issue by player1537** [henson-insitu/henson#2]
When I was working on Decaf-Henson, I kept running into an error in the Henson Python Puppet code that occurs when trying to set `sys.argv` when it already exists. In my setup, this would raise a Python exception, which gets handled by Python, but still propagated to pybind, and logged with the internal `spdlog` library. Due to an error on my end, spdlog doesn't work correctly, so I needed to get rid of all exceptions, even if they're otherwise harmless.

The fix looks like this:

```diff
diff --git a/include/henson/python-puppet.hpp b/include/henson/python-puppet.hpp
index 1aeb88c..7b126ca 100644
--- a/include/henson/python-puppet.hpp
+++ b/include/henson/python-puppet.hpp
@@ -61,7 +63,12 @@ struct PythonPuppet: public Coroutine<PythonPuppet>
                 self->start_time_ = get_time();
                 try
                 {
-                    auto argv = py::module::import("sys").attr("argv");
+                    py::list argv;
+                    if (py::hasattr(py::module::import("sys"), "argv")) {
+                        argv = py::module::import("sys").attr("argv");
+                    } else {
+                        py::module::import("sys").add_object("argv", argv);
+                    }
                     argv.attr("clear")();
                     for(size_t i = 0; i < self->arguments_.size(); ++i)
                     {
```

**Edit**: If you want, I can also format this as an actual pull request so it's easier to merge.

**Comment by mrzv** [comment]
Interesting. What version of Python are you using? Either way, a pull request would be great, so I can just merge it. Thanks.

**Comment by player1537** [comment]
I'm using Python 3.6.8 for this (by running `cmake -DPYBIND11_PYTHON_VERSION:STRING=3.6` and installing with `spack install python@3.6.8`).

I'll make a pull request then! :)

**Comment by mrzv** [comment]
Thanks!
